-- Tabla de usuarios por evento
CREATE TABLE IF NOT EXISTS "USR_VTAS" (
    "USR_EVNX" INTEGER      NOT NULL,
    "USR_IDEU" VARCHAR(20)  NOT NULL,
    "USR_NOMB" VARCHAR(100),
    "USR_PWDX" VARCHAR(100),
    "USR_ESTD" CHAR(1)      DEFAULT 'A',
    "USR_FCHI" INTEGER,
    "USR_FCHB" INTEGER,
    "USR_FCHD" INTEGER,
    "USR_FCHH" INTEGER,
    "USR_REFE" VARCHAR(100),
    "USR_FCHC" INTEGER,
    PRIMARY KEY ("USR_EVNX", "USR_IDEU")
);

-- Tabla de promocion de venta (precios por periodo)
CREATE TABLE IF NOT EXISTS "PVT_SORT" (
    "PVT_EVN"  INTEGER        NOT NULL,
    "PVT_FCHX" INTEGER        NOT NULL,
    "PVT_FCHD" INTEGER,
    "PVT_FCHH" INTEGER,
    "PVT_CHN1" NUMERIC(10,2),
    "PVT_CHN2" NUMERIC(10,2),
    "PVT_CHN3" NUMERIC(10,2),
    "PVT_CHN4" NUMERIC(10,2),
    "PVT_CHN5" NUMERIC(10,2),
    "PVT_CHN6" NUMERIC(10,2),
    "PVT_CHN7" NUMERIC(10,2),
    "PVT_CHN8" NUMERIC(10,2),
    "PVT_CHN9" NUMERIC(10,2),
    PRIMARY KEY ("PVT_EVN", "PVT_FCHX")
);
