from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ventas", "0011_inf_url")]

    operations = [
        migrations.RunSQL(
            sql="""
ALTER TABLE "EVN_DEF"
    ADD COLUMN IF NOT EXISTS "EVN_DFTCALL" VARCHAR(200),
    ADD COLUMN IF NOT EXISTS "EVN_DFTBARR" VARCHAR(100),
    ADD COLUMN IF NOT EXISTS "EVN_DFTPROV" VARCHAR(100),
    ADD COLUMN IF NOT EXISTS "EVN_DFTLOCA" VARCHAR(100),
    ADD COLUMN IF NOT EXISTS "EVN_DFTTID"  INTEGER,
    ADD COLUMN IF NOT EXISTS "EVN_DFTTPE"  INTEGER,
    ADD COLUMN IF NOT EXISTS "EVN_DFTCPOS" VARCHAR(20);
""",
            reverse_sql="""
ALTER TABLE "EVN_DEF"
    DROP COLUMN IF EXISTS "EVN_DFTCALL",
    DROP COLUMN IF EXISTS "EVN_DFTBARR",
    DROP COLUMN IF EXISTS "EVN_DFTPROV",
    DROP COLUMN IF EXISTS "EVN_DFTLOCA",
    DROP COLUMN IF EXISTS "EVN_DFTTID",
    DROP COLUMN IF EXISTS "EVN_DFTTPE",
    DROP COLUMN IF EXISTS "EVN_DFTCPOS";
""",
        ),
    ]
