from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ventas", "0012_evn_def_defaults")]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TABLE IF NOT EXISTS "app_core_departamento" (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dep_nombre      VARCHAR(200) NOT NULL,
    dep_codigo      VARCHAR(200) NOT NULL,
    dep_provincia_id BIGINT      NOT NULL,
    CONSTRAINT "app_core_departamento_dep_provincia_id_fk"
        FOREIGN KEY (dep_provincia_id) REFERENCES "app_core_provincia"(id)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS "app_core_departamento_dep_provincia_id_idx"
    ON "app_core_departamento" (dep_provincia_id);

ALTER TABLE "app_core_localidad"
    ADD COLUMN IF NOT EXISTS "loc_departamento_id" BIGINT,
    ADD CONSTRAINT "app_core_localidad_loc_departamento_id_fk"
        FOREIGN KEY (loc_departamento_id) REFERENCES "app_core_departamento"(id)
        DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX IF NOT EXISTS "app_core_localidad_loc_departamento_id_idx"
    ON "app_core_localidad" (loc_departamento_id);
""",
            reverse_sql="""
ALTER TABLE "app_core_localidad"
    DROP CONSTRAINT IF EXISTS "app_core_localidad_loc_departamento_id_fk",
    DROP COLUMN   IF EXISTS "loc_departamento_id";

DROP INDEX IF EXISTS "app_core_departamento_dep_provincia_id_idx";
DROP TABLE IF EXISTS "app_core_departamento";
""",
        ),
    ]
