from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ventas", "0017_evn_msgqr")]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TABLE IF NOT EXISTS "MSG_PROC" (
    "ID"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MSG_FCHA" DATE,
    "MSG_HORA" TIME,
    "MSG_IDPR" VARCHAR(30),
    "MSG_EVN"  INTEGER,
    "MSG_SEC"  INTEGER,
    "MSG_REFE" VARCHAR(200),
    "MSG_TXTO" VARCHAR(500),
    "MSG_MRKA" CHAR(1),
    "MSG_ERRO" VARCHAR(500)
);
""",
            reverse_sql='DROP TABLE IF EXISTS "MSG_PROC";',
        ),
    ]
